In [1]:
import numpy as np

In [3]:
import pandas as pd

# Questions on NumPy Array 

In [3]:
# 1.How to create an Empty and Full numpy array?
# Empty Array
list1 = []
arr1 = np.array(list1)
print(arr1)

# Full Array
arr2 = np.full([2,3],1)
print(arr2)

# Explanation :-
# An empty array is an array that has no value or is null.
# We can use the empty array later to append the values or modify them.

[]
[[1 1 1]
 [1 1 1]]


In [4]:
# 2.Create numpy array filled with all Zeros.
arr3 = np.zeros([2,3])
print(arr3)

# Explanation:-
# The numpy.zeros() function returns a new array of given shape and type, with zeros.

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 3.Create numpy array filled with all Ones.
arr4 = np.ones([3,3])
print(arr4)

# Explanation:-
# ones() function returns a new array of given shape and data type, where the element's value is set to 1.
# This function is very similar to numpy zeros() function.

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# 4.Check whether a numpy Array contains specified rows.
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
arr5 = np.array(l1)
l2 = [1,2,3]
l3 = [6,7,8]
print(arr5)
print(l2 in arr5.tolist())
print(l3 in arr5.tolist())

# Explanation:-
# If the given list is present in a NumPy array as a row then the output is True else False.
# The list is present in a NumPy array means any row of that numpy array matches with the given 
# list with all elements in given order

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
False


In [7]:
# 5.How to remove non-numeric rows from numpy array.
arr6 = np.array([[1,2,3],
                [4,np.nan,5],
                [6,7,np.nan],
                [4,5,np.nan],
                [7,8,9]])
print(arr6)
arr6[np.all(~np.isnan(arr6),axis=1)]

# axis 1=Row wise, 0=Column wise in whole array

# Explanation :- 
# Many times we have non-numeric values in NumPy array. These values need to be removed, so that array
# will be free from all these unnecessary values and look more decent. 
# It is possible to remove all rows containing Nan values using the Bitwise NOT operator and np. isnan() function.

[[ 1.  2.  3.]
 [ 4. nan  5.]
 [ 6.  7. nan]
 [ 4.  5. nan]
 [ 7.  8.  9.]]


array([[1., 2., 3.],
       [7., 8., 9.]])

In [8]:
# 6.remove a single-dimentional entries from shape of an array.
arr7 = np.array([[1],
                 [2],
                 [3]])
arr7_new = np.squeeze(arr7)
print(arr7)
arr7_new

# Explanation :-
# squeeze() function is used to remove single-dimensional entries from the shape of an array. 
# It returns an array with the same data but reshaped dimensions. 
# This function can be used to reduce the dimensions of an array, 
# which is useful for data preprocessing in machine learning applications.

[[1]
 [2]
 [3]]


array([1, 2, 3])

In [9]:
# 7.Find the number of accurences of a sequence in numpy array.
arr8 = np.array([1,2,3,4,5,1,1,2,6,6,6,6])
repr(arr8).count("6")

4

In [6]:
# 8.Find the most frequent value in numpy array
arr9=np.array([1,2,2,6,4,5,6,6,6,7,8,9,9,9,0,11,12,33,44,44,44,0,9,9,9,9,9,44,44,44,44,44,44,44,44,44,44,44])
mode=np.bincount(arr9)
print(mode)
mode1=np.argmax(mode)
print(mode1)

# Explanation :- 
# in above .bincount() function is used to count the occurence of each element in array
# .argmax() mathod to get a value having a maximum value of occurence(Frequency)

[ 2  1  2  0  1  1  4  1  1  8  0  1  1  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0 14]
44


In [18]:
# 9.Combining a one and two-dimensional numpy array
arr10=np.array([[1,2,3,4],
                [5,6,7,8]])
arr11=np.array([11,12,13,14])
print(arr10.shape)
print(arr11.shape)

reshaped=arr11.reshape(1,4)
combine=np.concatenate((arr10,reshaped),axis=0)
combine

# Explanation :- 
# First thing we have to get the shape of all array and then we have to reshape by same dimensions
# after that we can use .concatenate() function to combine two arrays.

(2, 4)
(4,)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14]])

In [29]:
# 10.How to build an array of all combinations of two Numpy arrays?
arr12=np.array([11,22])
arr13=np.array([33,44])

arr14=np.array(np.meshgrid(arr12,arr13)).T.reshape(-1,2)
print(arr14)

[[11 33]
 [11 44]
 [22 33]
 [22 44]]


Numpy

Functions

In [ ]:
# NumPy is a general-purpose array-processing package.
# It provides a high-performance multidimensional array object and tools for working with these arrays.


In [ ]:
# numpy.partition()
# numpy.argmax()
# numpy.extract()
# numpy.eye()
# numpy.T

1. Function = np.partition()

In [60]:
fn1= np.array([8,1,9,2,6,7,5,3,0,2,2,4,3])
part=np.partition(fn1,3)
print(part)

[2 0 1 2 2 3 4 3 5 7 6 9 8]


numpy.partition() function is used to create a partitioned copy of input array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

2. Function = np.argmax()

In [73]:
fn2=np.array([1,3,4,1,1,6,6,8,2,4,3,5,6,7,7,8,1,1,1,1,1,1,1])
arg=np.bincount(fn2)
ans = np.argmax(arg)
print(ans)


1


Explanation :- in above .bincount() function is used to count the occurence of each element in array .argmax() mathod to get a value having a maximum value of occurence(Frequency)

3. Function=np.extract()

In [75]:
fn3 = np.array([2,3,4,5,6,7,33,44,55,50,10])
# condition= fn3[fn3%2==0]
condition= np.mod(fn3,2)!=0
ans = np.extract(condition,fn3)
print('odd',ans)

odd [ 3  5  7 33 55]


extract. Return the elements of an array that satisfy some condition. This is equivalent to np.

4. Function = np.eye()

In [76]:
fn4= np.eye(6,k=2)
fn4

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Return a 2-D array with ones on the diagonal and zeros elsewhere.

5. Function = np.T

In [78]:
fn5 = np.arange(1,13,1)
fn5=fn5.reshape(3,4)
ans1=fn5.T.reshape(-1,2)
ans=fn5.T
print(ans1)
print(ans)

[[ 1  5]
 [ 9  2]
 [ 6 10]
 [ 3  7]
 [11  4]
 [ 8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


The . T attribute returns the transpose of a NumPy array as a new NumPy array without modifying the original array.